### ISSUE TITLE
Square maps with grid_size != tile_size

### ISSUE THREAD

**Issue by wideberg** [StarArawn/bevy_ecs_tilemap#204]
I would like to be able to use a tileset where the tile size differes from the grid size. However, it doesn't seem to be possible and I get the feeling that the grid_size is not taken into account when rendering.

I would expect the following example (tile_size=16x16, grid_size=8x8) to render sqaures with overlap but the tiles are aligned after the tile_size (see image) and not the grid_size. Setting grid size to 32 instead of 8 gives the same result.

```
    let mut settings = LayerSettings::new(
        MapSize(2, 2),
        ChunkSize(8, 8),
        TileSize(16.0, 16.0),
        TextureSize(96.0, 16.0),
    );
    settings.grid_size = Vec2::new(8.0, 8.0);
    let (mut layer_builder, _) = LayerBuilder::new(
        &mut commands,
        settings,
        0u16,
        0u16,
    );

    for i in 0..6 {
        let tile_pos = TilePos(i, i);
        let _ = layer_builder.set_tile(
            tile_pos,
            TileBundle {
                tile: Tile {
                    texture_index: i as u16,
                    ..Default::default()
                },
                ..Default::default()
            }
        );
    }
```

<img width="120" alt="image" src="https://user-images.githubusercontent.com/286843/181905041-88d7448a-eee6-4571-ae72-00e566953804.png">

**Comment by StarArawn** [comment]
Can you re-test this using the latest from main? I believe this should be fixed now.

**Comment by wideberg** [comment]
Hi, thanks for looking into it!
Strange enough it still doesn't seem to work properly. Changing the grid_size doesn't seem to do any change.

I've prepared an example for reproducing the issue if that would help (modified the basic.rs example)
https://github.com/wideberg/bevy_ecs_tilemap/tree/grid_size_issue

**Comment by wideberg** [comment]
I'm also not sure how the three values work together, TilemapSize, TilemapTileSize, TilemapGridSize.
Having a tilemap size of 4x4 (tiles), tile size of 16x16 (px) and a grid size of 8x8 (px) would in fact fit a total of 8x8 tiles due to the overlap, but with the total map size in pixels being 72x72px since the final row and column would overflow the expected size of 64x64 px.

**Comment by tigercat2000** [comment]
This happens because the [square shader](https://github.com/StarArawn/bevy_ecs_tilemap/blob/e144418676af050e668ccafed05ca66d806f6dfa/src/render/shaders/square.wgsl) doesn't incorporate `tilemap_data.grid_size` in `get_mesh` like [other shaders do](https://github.com/StarArawn/bevy_ecs_tilemap/blob/main/src/render/shaders/row_hex.wgsl#L13).

I believe this is a simple fix, but I'm still really shaky on computer graphics math, so I'm not exactly sure how to do it.

I did try, and realized that for the game_of_life example with it's grid_size changed to `vec2(16.0, 8.0)`, a naive multiplication against `position` just made things 16x farther apart on the x-axis and 8x apart on the y-axis. 

Need to somehow translate it to a 1-0 range based on the tile size, I think? As that vector should actually result in tiles being spaced normally in the x-axis and overlapping by 8 pixels in the y-axis.

**Comment by bzm3r** [comment]
> I would like to be able to use a tileset where the tile size differes from the grid size. However, it doesn't seem to be possible and I get the feeling that the grid_size is not taken into account when rendering.
> 
> I would expect the following example (tile_size=16x16, grid_size=8x8) to render sqaures with overlap but the tiles are aligned after the tile_size (see image) and not the grid_size. Setting grid size to 32 instead of 8 gives the same result.
> 
> ```
>     let mut settings = LayerSettings::new(
>         MapSize(2, 2),
>         ChunkSize(8, 8),
>         TileSize(16.0, 16.0),
>         TextureSize(96.0, 16.0),
>     );
>     settings.grid_size = Vec2::new(8.0, 8.0);
>     let (mut layer_builder, _) = LayerBuilder::new(
>         &mut commands,
>         settings,
>         0u16,
>         0u16,
>     );
> 
>     for i in 0..6 {
>         let tile_pos = TilePos(i, i);
>         let _ = layer_builder.set_tile(
>             tile_pos,
>             TileBundle {
>                 tile: Tile {
>                     texture_index: i as u16,
>                     ..Default::default()
>                 },
>                 ..Default::default()
>             }
>         );
>     }
> ```
> 
> <img alt="image" width="120" src="https://user-images.githubusercontent.com/286843/181905041-88d7448a-eee6-4571-ae72-00e566953804.png">

@wideberg can you try it again? We made some updates that allow it to work now. You'll have to use the `main` branch.

**Comment by bzm3r** [comment]
@wideberg @tigercat2000 thanks for pointing this out! A fix is on its way (see PR #243)

**Comment by wideberg** [comment]
I made a quick test with tilesize 16x16 and gridsize 8x8 which gave the result I expected:

<img width="106" alt="image" src="https://user-images.githubusercontent.com/286843/188005395-13de0cb4-dfc3-46e4-8bd5-563127b0d7b0.png">

An asymetric gridsize of 4x8 also seems to work correct:

<img width="98" alt="image" src="https://user-images.githubusercontent.com/286843/188005567-fa1a5f9f-902e-490f-a31a-b2ba3cae89c8.png">

Thanks a lot! Great job!!

**Comment by StarArawn** [comment]
Fixed by: #243
